spring:
  application.name: thumb-backend
  mvc:
    servlet:
      path: /api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thumb
    username: root
    password: 12345678

  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 5000

server:
  port: 8082

knife4j:
  enable: true
  setting:
    language: zh_cn

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl